import { writeFileSync, existsSync, lstatSync, readdirSync } from "fs";
import linq = require("linq");
import path = require("path");
import Action from "../Action";
import PathParser from "../Map/PathParser";
import ApiDocsBasePart from "./ApiDocsBasePart";
import ApiDocsConfig from "./ApiDocsConfig";
import ApiDocsMdCreater from "./ApiDocsMdCreater";
import ApiDocsNoteParser from "./ApiDocsNoteParser";

export default class ApiDocsCreater {
  constructor(
    private readonly cFolder: string,
    private readonly docsConfig?: ApiDocsConfig | string
  ) {
    if (
      !this.cFolder ||
      !existsSync(this.cfPath) ||
      !lstatSync(this.cfPath).isDirectory()
    ) {
      throw new Error(
        "please input controllers folder path, for example 'src/controllers'"
      );
    }
  }

  private get config(): ApiDocsConfig {
    if (!this.docsConfig) return {};
    if (typeof this.docsConfig == "string") {
      const configPath = path.join(process.cwd(), this.docsConfig);
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      return require(configPath) as ApiDocsConfig;
    } else {
      return this.docsConfig;
    }
  }

  get docs(): string {
    let result = "<!-- Automatically generated by CBA -->\n\n";
    const config = this.config;
    if (config.title) {
      result += `# ${config.title}\n\n`;
    }
    if (config.subtitle) {
      result += `${config.subtitle}\n\n`;
    }
    result += this.readFilesFromFolder("");
    if (result.lastIndexOf("---") > 0) {
      result = result.substr(0, result.length - 3);
    }
    result = result.trimEnd();
    result += "\n";

    return result;
  }

  public write(targetFile: string): void {
    if (!targetFile) {
      throw new Error(
        "please input target markdown file path, for example 'docs/api.md'"
      );
    }

    writeFileSync(path.join(process.cwd(), targetFile), this.docs);
  }

  private get cfPath(): string {
    return path.join(process.cwd(), this.cFolder);
  }

  private readFilesFromFolder(folderRePath: string): string {
    let result = "";
    const storageItems = linq
      .from(readdirSync(path.join(this.cfPath, folderRePath)))
      .select((item) => path.join(folderRePath, item))
      .toArray();

    const files = linq
      .from(storageItems)
      .where((storageItem) => {
        const stat = lstatSync(path.join(this.cfPath, storageItem));
        return (
          stat.isFile() &&
          (storageItem.endsWith(".js") || storageItem.endsWith(".ts"))
        );
      })
      .orderBy((item) => item)
      .toArray();
    for (let i = 0; i < files.length; i++) {
      const readFileResult = this.readFile(files[i]);
      if (readFileResult) {
        result += readFileResult;
        result += "\n\n---\n\n";
      }
    }

    const folders = linq
      .from(storageItems)
      .where((storageItem) => {
        const stat = lstatSync(path.join(this.cfPath, storageItem));
        return stat.isDirectory();
      })
      .orderBy((item) => item)
      .toArray();
    for (let i = 0; i < folders.length; i++) {
      result += this.readFilesFromFolder(folders[i]);
    }

    return result.trimEnd();
  }

  private readFile(relativePath: string): string {
    const file = path.join(this.cfPath, relativePath);
    let action;
    try {
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const actionClass = require(file).default;
      action = new actionClass() as Action;
      if (!action) return "";
    } catch (err) {
      console.log("require err", err.message);
      return "";
    }

    let docs;
    if (action.docs) {
      docs = action.docs;
    } else {
      docs = new ApiDocsNoteParser(file).docs;
    }
    if (!docs) return "";
    else return new ApiDocsMdCreater(relativePath, docs, this.config).result;
  }
}
