import { writeFileSync, existsSync, lstatSync, readdirSync } from "fs";
import linq = require("linq");
import path = require("path");
import { ApiDocs, ApiDocsParam } from "..";
import Action from "../Action";
import PathParser from "../Map/PathParser";
import ApiDocsConfig from "./ApiDocsConfig";
import ApiDocsInputParams from "./ApiDocsInputParams";
import ApiDocsOutputParams from "./ApiDocsOutputParams";
import ApiDocsParamsBase from "./ApiDocsParamsBase";

export default class ApiDocsCreater {
  constructor(
    private readonly cfPath: string,
    private readonly config: ApiDocsConfig = {}
  ) {
    if (
      !this.cfPath ||
      !existsSync(this.cfPath) ||
      !lstatSync(this.cfPath).isDirectory()
    ) {
      throw new Error(
        "please input controllers folder path, for example 'src/controllers'"
      );
    }
  }

  get docs(): string {
    let result = "<!-- Automatically generated by CBA -->\n\n";
    if (this.config.title) {
      result += `# ${this.config.title}\n\n`;
    }
    if (this.config.subTitle) {
      result += `${this.config.subTitle}\n\n`;
    }
    result += this.readFilesFromFolder("");
    if (result.lastIndexOf("---")) {
      result = result.substr(0, result.length - 3).trimEnd();
    }
    result += "\n";

    return result;
  }

  public write(targetFile: string): void {
    if (!targetFile) {
      throw new Error(
        "please input target markdown file path, for example 'docs/api.md'"
      );
    }

    writeFileSync(path.join(process.cwd(), targetFile), this.docs);
  }

  private readFilesFromFolder(folderRePath: string): string {
    let result = "";
    const storageItems = linq
      .from(readdirSync(path.join(this.cfPath, folderRePath)))
      .select((item) => path.join(folderRePath, item))
      .toArray();

    const files = linq
      .from(storageItems)
      .where((storageItem) => {
        const stat = lstatSync(path.join(this.cfPath, storageItem));
        return (
          stat.isFile() &&
          (storageItem.endsWith(".js") || storageItem.endsWith(".ts"))
        );
      })
      .orderBy((item) => item)
      .toArray();
    for (let i = 0; i < files.length; i++) {
      const readFileResult = this.readFile(files[i]);
      if (readFileResult) {
        result += readFileResult;
        result += "\n\n---\n\n";
      }
    }

    const folders = linq
      .from(storageItems)
      .where((storageItem) => {
        const stat = lstatSync(path.join(this.cfPath, storageItem));
        return stat.isDirectory();
      })
      .orderBy((item) => item)
      .toArray();
    for (let i = 0; i < folders.length; i++) {
      result += this.readFilesFromFolder(folders[i]);
    }

    return result.trimEnd();
  }

  private readFile(relativePath: string): string {
    const file = path.join(process.cwd(), this.cfPath, relativePath);
    let action;
    try {
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const actionClass = require(file).default;
      action = new actionClass() as Action;
      if (!action) return "";
    } catch (err) {
      return "";
    }

    if (!action.docs) return "";
    else return this.docsToMd(relativePath, action.docs);
  }

  private docsToMd(relativePath: string, docs: ApiDocs): string {
    let result = this.getTitle(relativePath, docs);
    result += "\n\n";
    result += this.getDesc(docs);
    result += "\n\n";

    if (docs.input) {
      result += "### Input\n\n";
      result += this.getInputParams(docs.input);
      result += "\n\n";
    }

    if (docs.output) {
      result += "### Output\n\n";
      result += this.getOutputParams(docs.output);
    }

    return result.trimEnd();
  }

  private getTitle(relativePath: string, docs: ApiDocs): string {
    const pathParser = new PathParser(relativePath);
    const httpMethod = pathParser.httpMethod;

    let result = `## `;
    result += `${httpMethod ? httpMethod : "ANY"}`;
    result += ` `;
    if (docs.name) {
      result += `${docs.name}`;
      result += `\n>`;
    }
    result += `/${pathParser.pathWithoutHttpMethodAndExtension}`;
    return result;
  }

  private getDesc(docs: ApiDocs) {
    if (!docs.desc) return "";
    let result = "### Desc \n\n";
    result += docs.desc || "Empty";
    return result;
  }

  private getInputParams(input?: ApiDocsInputParams): string {
    let result = "### Input\n\n";
    if (!input) {
      result += "No";
      return result;
    }

    result = this.getBaseParams(input, this.config.baseInputHeaders);
    result += "\n\n";

    const params = <ApiDocsParam[]>[];
    params.push(...(this.config.baseParams || <ApiDocsParam[]>[]));
    params.push(...(input.params || <ApiDocsParam[]>[]));
    if (params && params.length) {
      result += "#### Params\n\n";
      result += this.getParams(params);
      result += "\n\n";
    }

    if (input.query) {
      result += "#### Query\n\n";
      result += this.getParams(input.query);
      result += "\n\n";
    }

    return result.trimEnd();
  }

  private getOutputParams(output?: ApiDocsOutputParams): string {
    let result = "### Output\n\n";
    if (!output) {
      result += "No";
      return result;
    }

    result += `Status Code: ${output.code}\n\n`;
    result = this.getBaseParams(output, this.config.baseOutputHeaders);
    return result;
  }

  private getBaseParams(
    params: ApiDocsParamsBase,
    baseHeaders?: ApiDocsParam[]
  ) {
    let result = "";

    const headers = <ApiDocsParam[]>[];
    headers.push(...(baseHeaders || <ApiDocsParam[]>[]));
    headers.push(...(params.headers || <ApiDocsParam[]>[]));
    if (headers && headers.length) {
      result += "#### Headers\n\n";
      result += this.getParams(headers);
      result += "\n\n";
    }

    if (params.body) {
      result += "#### Body\n\n";
      if (Array.isArray(params.body)) {
        result += this.getParams(params.body);
      } else {
        result += this.getParam(params.body);
      }
      result += "\n\n";
    }

    return result.trimEnd();
  }

  private getParams(params: ApiDocsParam[]) {
    let result = "";
    for (let i = 1; i <= params.length; i++) {
      result += this.getParam(params[i - 1], 0, i);
      result += "\n";
    }
    return result.trimEnd();
  }

  private getParam(param: ApiDocsParam, depth = 0, index?: number): string {
    if (!param.name) return "";

    let result = this.padLeft(depth);

    if (index) {
      result += index;
      result += ". ";
    }
    result += param.name;

    if (param.type) {
      result += "\n";
      result += this.padLeft(depth + 1);
      result += "- Type: ";
      result += param.type;
    }

    if (param.desc) {
      result += "\n";
      result += this.padLeft(depth + 1);
      result += "- Desc: ";
      result += param.desc;
    }

    if (param.children) {
      result += "\n";
      result += this.padLeft(depth + 1);
      result += "- Children:";
      result += "\n";

      for (let i = 1; i <= param.children.length; i++) {
        result += this.getParam(param.children[i - 1], depth + 1, i);
        result += "\n";
      }
    }

    return result.trimEnd();
  }

  private padLeft(depth: number) {
    let result = "";
    for (let i = 0; i < depth; i++) {
      result += "   ";
    }
    return result;
  }
}
